Add RWD for footer
lukaszewczak/WDP-2010-01 pull request #14
Opened 2020-10-08 21:19 UTC by 111bioly

2020-10-09 04:43 UTC, lukaszewczak requested changes

2020-10-09 04:43 UTC, lukaszewczak commented on src/components/layout/Footer/Footer.module.scss
> +
Usun puste linie

2020-10-09 04:43 UTC, lukaszewczak commented on src/components/layout/Footer/Footer.module.scss
> +
Puste linie

2020-10-09 04:43 UTC, lukaszewczak commented on src/components/layout/Footer/Footer.module.scss
> +
Niepoterzebna pusta linia

2020-10-09 04:43 UTC, lukaszewczak commented on src/components/layout/Footer/Footer.module.scss
> +      .xxx {
Zmień proszę nazwę tej klasy, obecnie nic nam nie mówi

2020-10-09 04:43 UTC, lukaszewczak commented on src/components/layout/Footer/Footer.js
> +          <div className={'col-xl-4  col-md-12 ' + styles.xxx}>nn</div>
Rozumiem, że do testów wstawiłeś sobie tekst `nn` i spoko ale teraz go proszę usuń

2020-10-09 04:43 UTC, lukaszewczak commented on src/components/layout/Footer/Footer.js
> +          <img src='./images/cards.png' alt='Supported credit cards' />
Zmiana niby niewielka, ale wpływ na wyglad ma już spory, a na tabletach to się dobrze wyświetlało

Poniżej wkleiłem jak wygląda wersja na branchu `master`

![image](https://user-images.githubusercontent.com/7238770/95543975-3c1dec00-09fa-11eb-9f67-e3df316ac25f.png)

A tutaj jak wygląda Twoja wersja

![image](https://user-images.githubusercontent.com/7238770/95544017-5657ca00-09fa-11eb-9a62-a62239aeb6be.png)

2020-10-09 19:24 UTC, 111bioly commented
https://projects.kodilla.com/browse/WDP201001-18
Poprawiłem pod kątem tabletu mam nadzieje że teraz jest dobrze oraz usunąłem te odstępy, tekst, oraz zmieniłem nazwe klasy

2020-10-10 03:30 UTC, lukaszewczak approved these changes

2020-10-10 03:31 UTC, merged