Main menu with product search RWD added
lukaszewczak/WDP-2010-01 pull request #21
Opened 2020-10-11 13:07 UTC by MaciekLubocki

1/ Added RWD for Main Menu and Product Search

2020-10-11 19:14 UTC, lukaszewczak requested changes

2020-10-11 19:14 UTC, lukaszewczak commented on src/components/layout/MenuBar/MenuBar.module.scss
> +
Niepotrzebna pusta linia

2020-10-11 19:14 UTC, lukaszewczak commented on src/components/layout/MenuBar/MenuBar.module.scss
> +  height: 35px !important;
Po co te `!important` oraz dlaczego taki duży rozmiar dla tej ikony?

2020-10-11 19:14 UTC, lukaszewczak commented on src/components/layout/MenuBar/MenuBar.module.scss
> +
Pusta linia

2020-10-11 19:14 UTC, lukaszewczak commented on src/components/layout/MenuBar/MenuBar.module.scss
> +  margin: 10px -15px !important;
Po co ten `!important`?

2020-10-11 19:14 UTC, lukaszewczak commented on src/components/layout/MenuBar/MenuBar.module.scss
> +          }
Formatowanie, za dużo wcięć

2020-10-11 19:14 UTC, lukaszewczak commented on src/components/layout/MenuBar/MenuBar.module.scss
> +
Niepotrzebne jedna pusta linia

2020-10-11 19:14 UTC, lukaszewczak commented on src/styles/settings.scss
> +
Niepotrzebne puste linie

2020-10-11 19:18 UTC, MaciekLubocki commented on src/components/layout/MenuBar/MenuBar.module.scss
> +  height: 35px !important;
!important żeby wymusić rozmiar. bez tego nie chce mi dać żą
danego rozmiaru.

2020-10-12 04:21 UTC, lukaszewczak commented
Z uwagi na wprowadznie styleint proszę o aktualizacje z masterem przed mergem

2020-10-13 20:59 UTC, EdytaW reviewed
Moim zdaniem wszystkie kwestie wymagające zmian zostały wskazane

2020-10-14 03:27 UTC, lukaszewczak commented on src/components/layout/MenuBar/MenuBar.module.scss
> +  height: 35px !important;
TAk zgadza sę jest nadpisywana i widać w DevToolsach przez co, tak jak pisałem na kanele tu ma znaczneie specyficzność css-a i musiał byś napisać regułę o wyższej specyficznośći - do poczytania https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity

2020-10-14 15:00 UTC, lukaszewczak commented
Popraw konflikty. To zadanie musi poczekać wdrożenie #22

2020-10-16 04:01 UTC, lukaszewczak commented
Zadanie #22 zostało skończone, zaktualizuj się z masterem aby dokończyć to zadanie

2020-10-16 18:05 UTC, mariannasowi commented
jeszcze widze, ze sa jakies konflikty w settings, prosze spojrz :)

2020-10-20 21:58 UTC, mariannasowi commented
zmien prosze jeszcze tytul na nr taska/brancha np. WDP201001-(nr zadania)

2020-10-21 03:03 UTC, lukaszewczak requested changes
Popraw na wszystkich plikach w ramch tego zadania formatownie. Możliwe, że brak formatowanie wynika z faktu, żę tak długo ten PR- wisiał i część zmian jest sprzed dodania wymuszonego formatowania

2020-10-21 03:03 UTC, lukaszewczak commented on src/components/features/NewFurniture/NewFurniture.js
> -
Czemu ma służyć ta zmiana?

2020-10-21 03:03 UTC, lukaszewczak commented on src/components/features/ProductSearch/ProductSearch.js
> +  <div className={styles.center}>
Formatownie do poprawy

2020-10-21 03:03 UTC, lukaszewczak commented on src/components/features/ProductSearch/ProductSearch.module.scss
> +
Formatownie w tym pliku jest do poprawy. Nie dostałeś żadenego ostrzeżenia przy commitowaniu? Commit nie powinin sie udać

2020-10-21 03:03 UTC, lukaszewczak commented on src/components/features/ProductSearch/ProductSearch.module.scss
> +      select {
Po to właśnie należało poczekać na PR-a #22 który zmieniał strukturę, nie ma W ProductSearch tearaz elementu `<select>`

2020-10-21 03:03 UTC, lukaszewczak commented on src/components/layout/MenuBar/MenuBar.module.scss
> +      height: 100vh;
100vh nie jest potrzebne, bo dostajemy pod menu dużą białą przestrzeń. Dobrze jest przetestować jak to wygląda i dobrać odpowiednia wilkość

2020-10-21 03:03 UTC, lukaszewczak commented on src/styles/settings.scss
> +$white: #fff;
Do usunięcia

2020-10-21 13:16 UTC, MaciekLubocki commented on src/components/features/NewFurniture/NewFurniture.js
> -
Łukasz, nie kojarze tej zmiany...

2020-10-22 03:45 UTC, lukaszewczak commented
Popraw proszę konflikty

2020-10-22 03:48 UTC, lukaszewczak commented
Popracuj nad stylami, bo menu troche się rozjechało, przykład u Ciebie po najechaniu kursorem

![image](https://user-images.githubusercontent.com/7238770/96822237-e568d700-1429-11eb-81e9-f0014022e246.png)


A jak to wyglada od początku na branchu master 

![image](https://user-images.githubusercontent.com/7238770/96822342-1b0dc000-142a-11eb-9dbb-955fe66ffe85.png)


Dodanie RWD nie powinno wpłynąc aż tak mocno na bieżący stan

2020-10-23 17:52 UTC, lukaszewczak commented
Popraw proszę konflikty

2020-10-24 03:02 UTC, lukaszewczak approved these changes

2020-10-24 03:03 UTC, lukaszewczak commented
@mariannasowi @EdytaW Proszę o uwagi lub approve. Po usunięciu konfliktów zadanie bęidze gotowe do zmergowania

2020-10-24 11:14 UTC, MaciekLubocki commented
@lukaszewczak błędy poprawione.

2020-10-24 12:03 UTC, mariannasowi approved these changes

2020-10-24 16:27 UTC, merged