WDP201001-55
lukaszewczak/WDP-2010-01 pull request #24
Opened 2020-10-12 22:36 UTC by EdytaW

Usunięcie propsa addCompare. Infomracje o tym, czy produkt został dodany do porównywarki można odczytać ze zmiennej isProductAddedToCompare w ProductBox. Zmiana tła dla guzika odpowiedzialnego za wybór produktu do porównywarki.

2020-10-13 02:57 UTC, lukaszewczak requested changes

2020-10-13 02:57 UTC, lukaszewczak commented on src/components/common/ProductBox/ProductBox.js
> +    return isProductAddedToCompare;
Ta funkcja jest do obługi zdarzenia `click` nie powinna nic zwracać, wystarczy poniższy kod wyciągnąć poza ciało funkcji `compareHandler`.

```
const isProductAddedToCompare =
      compare.products &&
      compare.products.reduce(
        (accumulator, product) => accumulator || product.id === id,
        false
      );
```

2020-10-13 02:57 UTC, lukaszewczak commented on src/components/common/ProductBox/ProductBox.js
> +              className={compareHandler ? styles.productIsCompared : ''}
`compareHandler` to funkcja nie możesz jej tak użyć, to wyrażenie zawsze będzie zwracać `true`

2020-10-13 02:57 UTC, lukaszewczak commented on src/components/common/ProductBox/ProductBox.js
> +              className={compareHandler ? styles.productIsCompared : ''}
Druga sprawa to w zadaniu była informacja nt zmiany tła przycisku, ale do tego musisz przenieść ustawienie klasy na `<Button>` , bo w tym momencie uzyskany efekt nie jest zadawalający.

![image](https://user-images.githubusercontent.com/7238770/95810066-6a5c3e00-0d10-11eb-99f8-3c96f7cd33b2.png)

2020-10-13 10:33 UTC, koniecznytomek commented
@EdytaW Popraw 
```
compare.products &&
  compare.products.reduce ...
```

na

```
compare &&
  compare.products.reduce ...
```

Trzeba się pierw upewnić, czy obiekt `compare` istnieje.

2020-10-13 14:06 UTC, lukaszewczak requested changes

2020-10-13 14:06 UTC, lukaszewczak commented on src/components/common/ProductBox/ProductBox.js
> +  const isProductAddedToCompare =
Przerzuć tą deklarcję ponad metodę `compareHandler` bo dziwnie to wygląda, że w metodzie `comparehandler` odwołujemy się do zmiennej która jest deklarowana poniżej metody.

2020-10-13 14:06 UTC, lukaszewczak commented on src/components/common/ProductBox/ProductBox.js
> +    compare.products.reduce(
Dodaj jeszcze sprwdzenie, czy `compare.products` istnieje

2020-10-13 14:06 UTC, lukaszewczak commented on src/components/common/ProductBox/ProductBox.js
> +  products: PropTypes.array.isRequired,
Co to za props?

2020-10-13 17:37 UTC, koniecznytomek commented on src/components/common/ProductBox/ProductBox.js
> +    compare.products.reduce(
Edyta, moja propozycja:

```
    compare &&
    compare.products &&
    compare.products.reduce(
```

2020-10-13 19:04 UTC, lukaszewczak commented
Z uwagi na skończone zadanie #23 , zmerguje się prosze i wprowadź analogizne zmiany do kodu dp PromotedProduct

2020-10-13 19:05 UTC, BasiaM1 reviewed
wydaje mi się że wszystkie uwagi zostały już zgłoszone:)

2020-10-14 04:00 UTC, lukaszewczak commented
@EdytaW Widzę, że w komenatrzu wskzałame zły komponenet chodzi o `PromotedProductBox` aby jeszcze w nim poprawić analogiczny kod i pozbyc się tego propsa `addCompare`. Pomijam narazie fakt, że mamy zdublowaną funkcjonalność - ale na taki refaktor zrobimy oddzialne zadanie.

2020-10-14 07:53 UTC, lukaszewczak commented
@BasiaM1 @koniecznytomek @akijania Czy macie jeszcze jakieś uwagi? Jeżeli nie to proszę o akceptacje

2020-10-14 07:55 UTC, lukaszewczak approved these changes

2020-10-14 08:01 UTC, koniecznytomek approved these changes

2020-10-14 08:03 UTC, akijania approved these changes

2020-10-14 08:15 UTC, merged