WIP: WDP201001-35
lukaszewczak/WDP-2010-01 pull request #26
Opened 2020-10-13 14:58 UTC by EdytaW

Usunięcie wszystkich ostrzeżen eslinta podczas startu projektu.

2020-10-13 19:30 UTC, lukaszewczak requested changes

2020-10-14 05:04 UTC, lukaszewczak reviewed
Przy starcie projektu mamy jeszcze uwagi dla ./src/components/features/NewFurniture/NewFurniture.js

2020-10-14 05:56 UTC, koniecznytomek commented
@EdytaW według mnie przeniesienie metody `checkViewport` do cyklu powoduje, że będzie zwracana jej nowa wersja przy każdym rerenderze komponentu, czyli np przy zmianie szerokości okna. Nie ma potrzeby jej tam umieszczać. Lepiej owinąć ją w useCallbacka z odpowiednimy depsami, np:

```
  const checkViewport = useCallback(() => {
  ...
  }, [breakpoints.mobile, breakpoints.tablet]);
```

tablica zależności w drugim argumencie, informuje, że ma zostać zwrócona nowa wersja metody `checkViewport` tylko w momencie, kiedy zmienią się podane w niej wartości.

2020-10-14 14:23 UTC, lukaszewczak approved these changes

2020-10-14 14:23 UTC, lukaszewczak commented
@koniecznytomek @111bioly czy macie jeszcze jakieś uwagi? Jeżeli nie to proszę o akceptacje

2020-10-14 14:24 UTC, koniecznytomek approved these changes

2020-10-14 14:33 UTC, merged