WDP201001-23
lukaszewczak/WDP-2010-01 pull request #31
Opened 2020-10-14 18:20 UTC by koniecznytomek

### Info

Napisałem funkcjonalność do zadania WDP201001-22, którą można będzie zastosować do innych tasków zawierających slidery. `useSlider.js` jest reużywalnym custom hookiem, zwraca on następujące metody: `nextSlide`, `prevSlide`, `setSlide`, referencję: `slider`, aktualny stan / slider: `currentSlider`

### Sposób użycia

- importujemy hooka:
`  const { slider, setSlide, currentSlide } = useSlider(3, 10);` - przekazujemy do niego dwa argumenty, są to sekundy opóźnienia oraz pauzy. Jeżeli nie przekażemy żadnych argumentów, slider nie będzie się automatycznie przewijał.

- robimy destrukturyzację potrzebnych nam metod:
`const { slider, setSlide, currentSlide } = useSlider(3, 10);`

- dodajemy wrapper z referencją `ref={slider}`

```html
<div ref={slider}>
  <div>slide</div>
  <div>slide</div>
  <div>slide</div>
</div>
```

- opcjonalnie triggery do manualnego przewijania slidera:

```html
 <span onClick={() => setSlide(index)}></span>
 <span onClick={() => nextSlide()}></span>
 <span onClick={() => prevSlide()}></span>
```

Gdyby ktoś potrzebował więcej info, jak to działa, dlaczego użyłem useEffecty z różnymi depsami itd. to śmiało pytać. Krytyka mile widziana, z pewnością da się to nieco zwięźlej napisać.

Link do zadania:
https://projects.kodilla.com/browse/WDP201001-23

2020-10-14 20:15 UTC, akijania commented
Tomek, świetna robota! Super, że przy okazji posprzątałeś initialState i productRedux

2020-10-15 06:21 UTC, lukaszewczak requested changes
@koniecznytomek kawał dobrej roboty 👍 . Kilka drobiazgów zgłosiłem

2020-10-15 06:21 UTC, lukaszewczak commented on src/hooks/useSlider.js
> +    sliderLength = slider.current.childElementCount - 1;
Użycie `sliderLength` w ten spośob łamie regułę  `react-hooks/exhaustive-deps`  możesz użyć `useState` dla przechowania/ustawienia długości slidera

2020-10-15 06:21 UTC, lukaszewczak commented on src/hooks/useSlider.js
> +    sliderLength = slider.current.childElementCount - 1;
`slider.current` może byc nullem jeżeli ktoś nie wykorzysta go poprawnie albo jest w trakcie implementacji, w takim przypadku użytkownik dostanie błąd który może nie wiele powiedzieć, dlatego możęsz sam wyrzucić błąd albo tylko zalogować tą sytuacje na konsoli ewntualnie nic nie robić, poprstu slider nie bęidze działał, ale nie zaburzy pracy programisty

2020-10-15 06:21 UTC, lukaszewczak commented on src/hooks/useSlider.js
> +const useSlider = (delayTime, autoplayTime) => {
Proponuje ustawić watości domyślne na `0` i nie korzystać z nulli. Te parametry są przekazane do funkcji setTimeout, setInterval gdzie natrualnym argumentem przekazaznym jako timeout jest liczba a nie null

Wówczas w funkcjach wystarczy zapisać

```
  setTimeout(() => {
      setIsPause(false);
    }, autoplayTime * 1000);
```

2020-10-15 06:21 UTC, lukaszewczak commented
Popraw prosze konflikty

2020-10-15 06:24 UTC, lukaszewczak commented
@koniecznytomek propnuje dodać od razu funkcjonalność, zę po nacjechaniu myszką na boxa "hot deal" włączana jest pauza

2020-10-15 07:42 UTC, BasiaM1 reviewed
Tomek, super! :) fajnie, że można użyć tego slidera również do innych zadań.

2020-10-15 10:04 UTC, koniecznytomek commented
Muszę trochę więcej poczytać o useRef.

2020-10-15 19:36 UTC, lukaszewczak approved these changes

2020-10-15 19:37 UTC, lukaszewczak commented
@akijania Proszę a pprove jeżeli nie masz uwag

2020-10-16 07:45 UTC, akijania approved these changes

2020-10-16 07:59 UTC, merged