WDP201001-39
lukaszewczak/WDP-2010-01 pull request #38
Opened 2020-10-15 20:47 UTC by EdytaW

Użytkownik po kliknięciu w nazwę lub zdjęcie na karcie produktu lub po wpisaniu odpowiedniego url przechodzi do widoku produktu.Gdy zostanie podany nieodpowiedni url pokaże się informacja z kodem 404-not found oraz link do powrotu na stronę główną.W przypadku właściwego url na razie wystarczy, że na stronie pojawią się odpowiednie linki u góry (czyli nazwa kategorii oraz linki nawigujące) oraz nazwa szukanego produktu poniżej. 

Link do zadania: https://projects.kodilla.com/browse/WDP201001-39

2020-10-16 03:59 UTC, lukaszewczak requested changes

2020-10-16 03:59 UTC, lukaszewczak commented on src/components/common/ProductBox/ProductBox.js
> +  let url = '/product/' + { id };
Zapisując wyrażenie `{ id }` wykorzystałaś opcję wprowadzoną wraz ze standardem EcmaScript2015 do stworzenia obiektu korzystając ze skrótowego zapisu właściwości . W efekcie to wyrażenie równoważane jest takiemu zapisowi
```
{
  id: id
}
```

Do poczytania https://alligator.io/js/object-property-shorthand-es6/

Wystarczyło by to zapisać tak `'/product/' + id;` i możesz to bezpośrednio zapisać w komponenecie `<Link>`

Możesz też wykorzystać template literals do zapisania adresu https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals

2020-10-16 18:12 UTC, mariannasowi commented
Edyta spojrz prosze na konflikty :)

2020-10-17 06:45 UTC, lukaszewczak requested changes
Brakuje mi tu jeszcze zmian, na poziomie komponenetu ` ProductPage`, przede wszystkim aby pokazać komponenet `NotFound` jeżeli produkt o danym id nie został znaleziony

2020-10-17 06:45 UTC, lukaszewczak commented on src/App.js
> +          <Route path='*' component={NotFound} />
Ta reguła musi być ostatnia, po mergu wskoczyła definicja ścieżki dla bloga, przez co  przy obecnej kolejnośći nie można wejść na widok pojedyńczego bloga

2020-10-17 06:45 UTC, lukaszewczak commented on src/components/common/ProductBox/ProductBox.js
> +import ProductPage from '../../views/ProductPage/ProductPage';
Dlaczego zaimportowałaś tutaj `ProductPage`?

2020-10-17 06:45 UTC, lukaszewczak commented on src/components/views/ProductPage/ProductPageContainer.js
> +    columns: getProductById(state, id),
W `productsRedux` zdefiniowałaś funkcję `getProductByI` któa to szuka nam prouktu o wskazanym **id**, a w tym momencie wównież tutaj masz analogiczny kod do szukania produktu. 

Nie rozumiem też tej właściwości `columns`, czemu miała by służyć?

2020-10-17 06:58 UTC, lukaszewczak commented
Brakuje tez implementacji `W przypadku właściwego url na razie wystarczy, że na stronie pojawią się odpowiednie linki u góry (czyli nazwa kategorii oraz linki nawigujące) oraz nazwa szukanego produktu poniżej. `

2020-10-17 13:14 UTC, BasiaM1 reviewed
Przechodzenie na widok produktu działa:) jednak nie jestem pewna czy działa to wyświetleniem informacji z kodem 404-not found, bo jak próbuję to zasymulować czyli wpisuje "http://localhost:3000/product/vb" to i tak wyswietal mi się widok produktu tyle że bez zdjęcia...ale może ja nie umiem tego zasymulować...

2020-10-17 17:31 UTC, lukaszewczak requested changes

2020-10-17 17:31 UTC, lukaszewczak commented on src/components/views/ProductPage/ProductPage.module.scss
> +  position: absolute;
Zdejmij pozycje absolute z tego elementu, bo ona właśnie sprawia, że układ sie rozpada

2020-10-17 17:31 UTC, lukaszewczak commented on src/components/views/ProductPage/ProductPage.js
>        <div className='container'>
Dodaj do tego kontenera klasę z `position: relative` i korzystając z właściwości `top` przesuń ją np o -14px,

2020-10-17 18:53 UTC, lukaszewczak requested changes

2020-10-17 18:53 UTC, lukaszewczak commented on src/components/views/ProductPage/ProductPage.js
> +      <div className='container product'>
Aby użyć klasy product dla tego komponenetu, należy skorzystać ze `styles.product`

2020-10-18 05:39 UTC, lukaszewczak requested changes

2020-10-18 05:39 UTC, lukaszewczak commented on src/components/views/ProductPage/ProductPage.module.scss
> +  background-color: white;
Kolor do zmiennej

2020-10-18 05:39 UTC, lukaszewczak commented on yarn.lock
> +=======
Żle zmergował się plik yarn.lock. Najszybcięj będize go usunąć i wywołać komendę `yarn install` aby zostął wygenerowany nowy plik yarn.lock

2020-10-18 05:39 UTC, lukaszewczak commented on src/components/views/ProductPage/ProductPage.module.scss
> +.product {
Tutaj należy dodać ` padding: $base-padding 0;` i jednocześnie usunąć padding z  selektora `.root`. Piwerwsza wersja strony produktowej nie zawierała tego top bara i była tylko na białym tle, ale jak doszedł nagłówek, to zgodnie z projektem pomiędzy nagłówkiem a głóewnym menu nie ma przestrzeni

![image](https://user-images.githubusercontent.com/7238770/96359473-89ddd700-1113-11eb-92b6-7bb6d70f06e2.png)

2020-10-18 05:39 UTC, lukaszewczak commented on src/components/views/ProductPage/ProductPage.js
> +          <ul>
Należy osadzić to w `.container` aby treść zawierała tą samą szerokość co opis produktu

2020-10-18 05:39 UTC, lukaszewczak commented on src/components/views/ProductPage/ProductPage.module.scss
> +        font-size: 20px;
Zmniejsz proszę ten rozmiar czcionki aby odpowiadał projektowi

![image](https://user-images.githubusercontent.com/7238770/96359507-f3f67c00-1113-11eb-8ad5-5acb62f25b25.png)

2020-10-18 05:39 UTC, lukaszewczak commented on src/components/views/ProductPage/ProductPage.js
> +            <li className='col-8'>FURNITURE</li>
To nie poinno być w tej liście, tylko raczej jako nagłówek `<h2>` występować poza listą

2020-10-18 05:39 UTC, lukaszewczak commented on src/components/views/ProductPage/ProductPage.js
> +            <li className='col-1'>
Nie korzystaj z `col-x` dla elementów `<li>`

2020-10-18 12:04 UTC, lukaszewczak requested changes
Tylko treść navbara powinna być ograniczona kontenerem a nie cały navbar

2020-10-18 16:44 UTC, lukaszewczak requested changes

2020-10-18 16:44 UTC, lukaszewczak commented on src/components/views/ProductPage/ProductPage.js
> +              <h2>FURNITURE</h2>
Element `<h2>` nie może być bezpośrednim dzieckiem listy `<ul>`. Umieść nagłówek poza listą

2020-10-18 16:44 UTC, lukaszewczak commented on src/components/views/ProductPage/ProductPage.module.scss
> +      content: "\00BB";
TEn element nie odpoiada projektowi graficznemu proponuje w liście `ul/li` wykorzystać `<FontAwesomeIcon icon={faAngleRight}></FontAwesomeIcon>`

2020-10-18 22:13 UTC, mariannasowi commented
Super Edyta :) najs

2020-10-18 22:14 UTC, mariannasowi approved these changes

2020-10-19 02:58 UTC, lukaszewczak approved these changes

2020-10-19 02:58 UTC, merged