WDP201001-31
lukaszewczak/WDP-2010-01 pull request #46
Opened 2020-10-18 22:04 UTC by mariannasowi

https://projects.kodilla.com/browse/WDP201001-31
Cos podlubalam, ale niestety animacja slidera nie dziala, prosze o code review

2020-10-19 04:28 UTC, lukaszewczak requested changes

2020-10-19 04:28 UTC, lukaszewczak commented on src/components/features/Brands/Brands.js
> +            {renderPages}
renderPages to funkcja więc wymaga wywołania, ale ta funkjca nie jest specjalnie potrzeban dlatego możesz odwołać się tutaj do tabliecy `pages` bezpośrednio

2020-10-19 04:28 UTC, lukaszewczak commented on src/components/features/Brands/Brands.js
> +              ))}
Tutaj powinin pojawić się komponent Swipe

2020-10-19 04:28 UTC, lukaszewczak commented on src/components/features/Brands/Brands.js
> +    const pagesCount = Math.ceil(brands.length / brandsNumberOnSlide);
Usuń proszę kod związany z ustaleniem liczby pokazywanych elementó na urzędzaniu, to zostanie obsłużone w zadaniu RWD dla tej sekcji, a teraz przyjmij że prezentowanych jest porpstu 6 elementów na stronie i skup sie proszę na osbsłudze przełączania strzałek

2020-10-19 04:28 UTC, lukaszewczak commented on src/components/features/Brands/Brands.js
> +  getBrandsCountFromMode(mode) {
Do usunięcia

2020-10-20 17:35 UTC, lukaszewczak requested changes

2020-10-20 17:35 UTC, lukaszewczak commented on src/components/features/Brands/Brands.js
> +              <FontAwesomeIcon className={styles.icon} icon={faAngleLeft} />
Do starzłki nie jest podpięta akcja przesunięcia w lewo

2020-10-20 17:35 UTC, lukaszewczak commented on src/components/features/Brands/Brands.js
> +              <FontAwesomeIcon className={styles.icon} icon={faAngleRight} />
Do starzłki nie jest podpięta akcja przesunięcia w prawo

2020-10-20 17:35 UTC, lukaszewczak commented on src/components/features/Brands/Brands.js
> +            <SwipeComponent
Ddoanie swipe popsuło wygląd komponentu, trzeba przeciążyć style kontenra swipe aby przywrócić poprzedni wygląd

2020-10-20 18:16 UTC, mariannasowi commented
@lukaszewczak sporo wczesniej juz zmienilam, ale dopiero teraz wrzucam tutaj, strzalki chodza, zdjecia sie przesuwaja, mam dwie zagwostki 1- nie wyswietlaja sie foty 2-dlaczego prawa strzalka jest ponizej?

2020-10-21 02:33 UTC, lukaszewczak requested changes

2020-10-21 02:33 UTC, lukaszewczak commented on src/components/features/Brands/Brands.js
> +            <div className={styles.brandBox}>
Pisałem już o tym, Dodanie swipe popsuło wygląd komponentu, trzeba popracować nad stylami aby przywrócić poprzedni wygląd

2020-10-21 02:33 UTC, lukaszewczak commented on src/components/features/Brands/Brands.js
> +              <img src={brands.image} alt={brand.name} />
Do zmiany `src={brands.image}`  => src={brand.image}

2020-10-22 03:40 UTC, lukaszewczak approved these changes
Śmiga :-) 👍

2020-10-22 03:40 UTC, lukaszewczak commented
@BasiaM1 @akijania @EdytaW prosze o uwagi lub approve

2020-10-22 06:48 UTC, akijania approved these changes

2020-10-22 06:52 UTC, merged