WDP201001-24
lukaszewczak/WDP-2010-01 pull request #47
Opened 2020-10-19 18:08 UTC by akijania

Link do zadania: [WDP201001-24](https://projects.kodilla.com/browse/WDP201001-24)
Na małych i średnich ekranach nie będzie wyświetlana sekcja HotDeal w PromotedProducts. 
Zdjęcie po prawej stronie będzie wyświetlane na całej szerokości ekranu. Dodałam funkcjonalność przesuwania slajdów za pomocą komponentu Swipeable, stóra znajduje się w pliku PromotedProductSwipe.

2020-10-20 17:28 UTC, BasiaM1 reviewed
W wersji mobilnej jest widoczny tylko prawy slider czyli zgodnie z zadaniem:) natomiast samo przesuwanie slajdów działa ale w prawo trzeba kliknąć dwa razy, żeby pokazał się inny obraz, czy to ok?

2020-10-20 17:39 UTC, akijania commented
> W wersji mobilnej jest widoczny tylko prawy slider czyli zgodnie z zadaniem:) natomiast samo przesuwanie slajdów działa ale w prawo trzeba kliknąć dwa razy, żeby pokazał się inny obraz, czy to ok?

Wiem, że coś jest nie tak z przesuwaniem slajdów ale nie wiem jak to naprawić :( Może Łukasz coś podpowie.

2020-10-20 17:54 UTC, BasiaM1 commented
no wlasnie, ja też niestety nie wiem o co chodzi:(

2020-10-20 17:56 UTC, lukaszewczak commented
Tylko, że to bardzo ładnie działa @akijania @BasiaM1 :-) jeżeli korzystacie z DevToolsów w Chrome to faktycznie tam jest słabo ale to wynika z narzędzia, ale np FireFox jest elgancko i bezpośrednio na telefonie proponuej sprawdzić u mnie śmiega :-)

2020-10-20 18:02 UTC, lukaszewczak requested changes

2020-10-20 18:02 UTC, lukaszewczak commented on src/components/features/PromotedProduct/PromotedProductSwipe.js
> +  handlePageChange(newPage) {
Nie używasz tej funkcji, dlatego można ją usunąć, w efekcie nie potrzebujesz też propsa `manualPageChange`

2020-10-20 19:33 UTC, EdytaW approved these changes

2020-10-20 19:48 UTC, BasiaM1 commented
rzeczywiście na firefoxie działa dobrze:)

2020-10-21 02:22 UTC, lukaszewczak approved these changes

2020-10-21 02:22 UTC, merged