WDP201001-68
lukaszewczak/WDP-2010-01 pull request #50
Opened 2020-10-20 12:17 UTC by koniecznytomek

Napisałem komponent CartMini, który jest listą produktów dodanych do koszyka w postaci bocznego, wysuwanego panelu, i z którego będzie przechodzić się do koszyka głównego z podsumowaniem zakupu.

Panel z koszykiem aktywowany jest podczas dodawania produktu, oraz poprzez kliknięcie ikony koszyka w headerze. Zamknąć można poprzez ikonkę zamknięcia w panelu lub  klikając poza koszykiem w przeźroczysty overlay. Koszyk zamknie się również po usunięciu wszystkich produktów z listy.

Kiedy panel jest aktywny przewijanie strony jest zablokowane, można natomiast przewijać listę w koszyku, kiedy jego długość przekroczy długość ekranu.

Link do zadania:
https://projects.kodilla.com/browse/WDP201001-68

2020-10-21 15:50 UTC, akijania commented
Kawał dobrej roboty! Strasznie mi się podoba jak zrobiłeś ten koszyk i jestem pod wrażeniem bo sama bym tego nie potrafiła zrobić! Niestety nie działają 2 rzeczy. Nie wiem czy są tematem zadania czy nie ale skoro masz już komplet i znalazłbyś czas to może mógłbyś je dodać. 
1. Gdy wchodzisz na podstronę naszego projektu to produkty z listy znikają
2. Nie działa dodawanie produktów ze strony produktu

2020-10-21 18:07 UTC, koniecznytomek commented
> 1. Gdy wchodzisz na podstronę naszego projektu to produkty z listy znikają
> 2. Nie działa dodawanie produktów ze strony produktu

Ania, dziękuję, wbrew pozorom to nic wielkiego :) Jutro zerknę na te dwa punkty.

2020-10-22 07:44 UTC, koniecznytomek commented
Ania, już wiem, o co Ci chodzi. Tak, stan reduksowy domyślnie kasuje się po odświeżeniu strony i wtedy produkty znikają z koszyka. Żeby zachować stan można użyć biblioteki `redux-persist`. Teraz jak zobaczysz podgląd, to produkty pozostają na miejscu po przeładowaniu witryny.

Można to wykorzystać do trzymania innych stanów. Wystarczy w pliku `store.js` dodać do "whitelist" odpowiedni reduktor:

```js
const persistConfig = {
  key: 'root',
  storage,
  whitelist: ['cart'],
};
```

2020-10-22 11:17 UTC, akijania commented
Tomek. Podzieliłam ProductPage na komponenty więc po zmergowaniu któryś z nas będzie musiał odrobinę zmienić.

2020-10-22 11:32 UTC, akijania commented
W karcie produktu można wybrać ilość produktów, które chcemy dodać do koszyka. Proponuję zrobić na to nowego taska.

2020-10-22 11:35 UTC, akijania approved these changes

2020-10-22 12:39 UTC, mariannasowi approved these changes

2020-10-22 15:30 UTC, BasiaM1 approved these changes

2020-10-23 07:58 UTC, lukaszewczak requested changes
Tomku świetna robota :-) 👍 , zgłosiłem kilka niuansów do korekty.

2020-10-23 07:58 UTC, lukaszewczak commented on src/components/features/CartMini/CartMini.js
> +    const summaryPrice = calcSummaryPrice();
Czy nie wystarczy zapisać tego operatorem warunkowy `typeof quantity != 'undefined' ? quantity * price : price` ? Tej funkcji `calcSummaryPrice` więcej nie używasz

2020-10-23 07:58 UTC, lukaszewczak commented on src/components/features/CartMini/CartMini.js
> +      document.body.classList.add('slide');
Tu już się trochę za dużo dzieje, i sprawdzanie warunków i logika proponuje zrobić poczciwego if-a

2020-10-23 07:58 UTC, lukaszewczak commented on src/components/features/CartMini/CartMini.js
> +        {products.length === 0 && (
Sprawdź najpierw czy `products` istnieje

2020-10-23 07:58 UTC, lukaszewczak commented on src/components/features/CartMini/CartMini.module.scss
> +@import "../../../styles/settings.scss";
Zwróć proszę uwagę, że wpliku scss korzystasz ze zmiennych które są oznakowane w plikut settings jako te których nie używamy bezpośrednio w projekcie. Swtórz dedykowaną grupę zmiennych dla koszyka

2020-10-23 07:58 UTC, lukaszewczak commented on src/redux/cartRedux.js
> +      const setTotalPrice = (statePart.totalPrice += action.payload.price);
Zamiast `statePart.totalPrice += action.payload.price` wystarczy `statePart.totalPrice + action.payload.price` bo w tym momencie modyfikujesz już stan, co w innej sytuacji mogło by mieć nieprzyjemne skutki

2020-10-23 07:58 UTC, lukaszewczak commented on src/redux/cartRedux.js
> +        ? statePart.products.filter(product => {
Tu potrzebujesz zmodyfikowac instiejącą tablicę dlatego lepszym wyborem jest użycie operatora `map` nie zwracasz tutaj przefiltrowanje tablicy

2020-10-23 07:58 UTC, lukaszewczak commented on src/redux/cartRedux.js
> +            return [statePart.products];
Jak używamy operaotra `filter` to jego callback ma zwrócić tylko true lub false, zwrócenie tablicy samo w sobie nic nie daje, po za tym, że zwracana wartość jest trakowana jak true

2020-10-23 07:58 UTC, lukaszewczak commented on src/redux/cartRedux.js
> +      const setTotalPrice = (statePart.totalPrice += action.payload.price);
Dlaczego nazwałeś tą zmienną `setTotalPrice`? To bardziej kojarzy się z funkcją niż ze zmienną

2020-10-23 07:58 UTC, lukaszewczak commented on src/redux/cartRedux.js
> +      const newStatePart = statePart.products.filter(product => {
Podobna sytuacja jak wcześniej, nie filtrujemy tutaj tablicy tylko ją modyfikujemy czyli zamiast `filter` użyj `map`

2020-10-23 07:59 UTC, lukaszewczak commented on src/components/features/CartMini/CartMini.js
> +                </div>
Warto rozwarzyć stworznie komponenety typu `CartItem` zawierający przezentację produktu w koszyku

2020-10-24 18:40 UTC, EdytaW approved these changes

2020-10-24 18:42 UTC, mariannasowi commented
jakies konflikty jeszcze wyskoczyly

2020-10-26 04:29 UTC, lukaszewczak approved these changes

2020-10-26 04:30 UTC, merged