Hot Deals - odliczanie czasu do końca promocji
lukaszewczak/WDP-2010-01 pull request #51
Opened 2020-10-20 15:41 UTC by MaciekLubocki

Dodanie komponentu liczączego czas do końca promocji. Treść zadania znajduje się pod adresem:
https://projects.kodilla.com/browse/WDP201001-72

2020-10-21 02:42 UTC, lukaszewczak requested changes

2020-10-21 02:42 UTC, lukaszewczak commented on src/components/common/PromotedProductTimeCounter/PromotedProductTimeCounter.js
> +const PromotedProductTimeCounter = ({ endTime }) => {
Brakuje definicji prop types dla propsa `endTime`

2020-10-21 02:42 UTC, lukaszewczak commented on src/components/common/PromotedProductTimeCounter/PromotedProductTimeCounter.js
> +  }, [currentTime]);
Hook useEffect korzysta jeszcze z timeDiff oraz productEndTime, powinny być wskazane w tablicy zależnośći

2020-10-21 07:26 UTC, koniecznytomek commented
Moim zdaniem nie ma potrzeby tworzenia tylu useStatów. Zamiast tego można utworzyć jeden z obiektem zawierającym wszystkie składowe timera.

`const [timer, setTimer] = useState({});`

2020-10-21 07:27 UTC, koniecznytomek commented on src/components/common/PromotedProductTimeCounter/PromotedProductTimeCounter.js
> +    return <p>Promotion os over</p>;
Literówka :)

2020-10-21 15:39 UTC, akijania commented
Super wygląda i działa na stronie :)

2020-10-22 03:42 UTC, lukaszewczak approved these changes
Bardzo fajnie 👍

2020-10-22 03:42 UTC, lukaszewczak commented
@koniecznytomek @akijania prosze o uwagi lub approve

2020-10-22 05:43 UTC, koniecznytomek approved these changes

2020-10-22 06:52 UTC, akijania approved these changes

2020-10-22 07:01 UTC, merged