Wdp201001-46
lukaszewczak/WDP-2010-01 pull request #52
Opened 2020-10-20 16:51 UTC by MaciekLubocki

Stworzyłem belkę z opcjami dla listy produktów. Belka była testowana na komponencie NewFurniture z powodu braku docelowego widoku. Finalnie do repozytorium przesłałem niepodpięty komponent.

Link do zadania:
https://projects.kodilla.com/browse/WDP201001-46

2020-10-21 03:10 UTC, lukaszewczak requested changes
Wygląda poprawnie, może jutro bęidze już lista produktów to bęidze można od razu to osadzić

2020-10-21 03:10 UTC, lukaszewczak commented on src/components/common/ControlBar/ControlBar.js
> +          <FontAwesomeIcon className={styles.icon} icon={faThList} />
W projekcie graficnym nie ma checkboxów

2020-10-23 03:16 UTC, lukaszewczak commented
Widok listy produktów jest przygotowany, możesz już osadzić ten komponenet

2020-10-23 08:25 UTC, akijania commented on src/components/common/ControlBar/ControlBar.js
> +const ControlBar = props => {
Używasz gdzieś te propsy?

2020-10-23 08:25 UTC, akijania commented on src/components/common/ControlBar/ControlBar.js
> +
pusta linia

2020-10-24 09:24 UTC, MaciekLubocki commented on src/components/common/ControlBar/ControlBar.js
> +const ControlBar = props => {
Ania dziękuję, już poprawiłem.

2020-10-24 09:26 UTC, MaciekLubocki commented on src/components/common/ControlBar/ControlBar.js
> +
poprawiłem

2020-10-24 16:49 UTC, lukaszewczak approved these changes

2020-10-24 16:50 UTC, lukaszewczak commented
@BasiaM1 @EdytaW @akijania Proszę o uwagi lub approve

2020-10-24 16:58 UTC, lukaszewczak requested changes
Usuń pusty plik src/components/common/ControlBar/ControlBarContainer.js

2020-10-24 17:16 UTC, akijania approved these changes

2020-10-24 18:29 UTC, EdytaW approved these changes

2020-10-25 10:16 UTC, MaciekLubocki commented on src/components/common/ControlBar/ControlBar.js
> +          <FontAwesomeIcon className={styles.icon} icon={faThList} />
już jest poprawione @lukaszewczak

2020-10-25 13:47 UTC, MaciekLubocki commented
@lukaszewczak ControlBarContainer.js zostal usuniety. Niestety pod komentarzem nie bylem w stanie dodac odpowiedzi... Usunalem takze konflikty. Czy mozemy juz mergowac ta galaz? :) Nie widze innych uwag..

2020-10-25 14:22 UTC, lukaszewczak approved these changes

2020-10-25 14:23 UTC, merged