WDP201001-28
lukaszewczak/WDP-2010-01 pull request #53
Opened 2020-10-20 19:12 UTC by EdytaW

Link do zad: https://projects.kodilla.com/browse/WDP201001-28

Dodałam funkcjonalność do zmiany tabów oraz przesuwanie slidera po kliknięciu strzałek. 

Mam problem z dodaniem animacji fade.

2020-10-21 03:32 UTC, lukaszewczak requested changes
Odnośnei animacji fade , przeanlizuj jak to zostąło zrobione np w komponenecie PromotedProduct

2020-10-21 03:32 UTC, lukaszewczak commented on src/redux/initialState.js
> +      // topSeller: true,
Nie zostawiej zakomentowanego kodu

2020-10-21 15:24 UTC, akijania commented
Edytko, super robota! Działa zmienianie tabów, wybieranie zdjęć i przesuwanie slidera. Jedyne co mi przeszkadza to gdy klikniemy na tab, który nie ma zdjęcia, galeria się trochę rozsypuje. Nie jest to chyba tematem Twojego zadania więc może zrobić na to osobnego PR?

2020-10-22 03:31 UTC, lukaszewczak commented
Popraw proszę konflikty

2020-10-22 19:09 UTC, lukaszewczak approved these changes

2020-10-22 19:10 UTC, lukaszewczak commented
@akijania @BasiaM1 @koniecznytomek Dajcie proszę uwagi lub approve. Temat fade przeniesiemy do innego zadania.

2020-10-22 19:54 UTC, akijania approved these changes

2020-10-23 03:02 UTC, lukaszewczak commented
@EdytaW Popraw proszę konflikty

2020-10-23 05:32 UTC, koniecznytomek approved these changes

2020-10-23 15:37 UTC, EdytaW commented
> @EdytaW Popraw proszę konflikty

nie pokazuje mi konfliktów

2020-10-23 16:06 UTC, merged