WDP201001-73
lukaszewczak/WDP-2010-01 pull request #56
Opened 2020-10-22 11:15 UTC by akijania

Link do zadania: [WDP201001-73](https://projects.kodilla.com/browse/WDP201001-73)
Podzieliłam ProductPage na komponenty.

2020-10-22 19:04 UTC, lukaszewczak requested changes
Aniu bardzo fajnie, to rozbiłaś, drobną zmianę jeszcze zaproponowałem. Zwróc też proszę uwagę, aby te nowe komponenty przenieść do folderu `features` bo `views` jest przeznaczony dla widoków.

2020-10-22 19:04 UTC, lukaszewczak commented on src/components/views/ProductPage/ProductPage.js
>          <div className='container'>
Proponuje całą tą część przenieść do własnego komponenetu, dzięki temu na stornie produktu powistana niezależne komponenety odpoweidizalne za każdy fragment strony

2020-10-22 20:07 UTC, akijania commented on src/components/views/ProductPage/ProductPage.js
>          <div className='container'>
> Proponuje całą tą część przenieść do własnego komponenetu, dzięki temu na stornie produktu powistana niezależne komponenety odpoweidizalne za każdy fragment strony

chodzi o cały kontener czy o sekcję ze zdjęciami?

2020-10-22 20:14 UTC, lukaszewczak commented on src/components/views/ProductPage/ProductPage.js
>          <div className='container'>
Cały kontener , nie miałem jak tego zaznaczyć dobrze

2020-10-23 08:03 UTC, lukaszewczak approved these changes
👍

2020-10-23 10:17 UTC, koniecznytomek approved these changes

2020-10-23 15:09 UTC, MaciekLubocki approved these changes

2020-10-23 15:14 UTC, merged