WDP201001 41
lukaszewczak/WDP-2010-01 pull request #57
Opened 2020-10-22 16:17 UTC by BasiaM1

Stworzyłam 2-gi widok produktu w ProductPage.js Poprawiłam spacje w Gallery scss, bo stylelint rzucał błąd. Link do zadania: https://projects.kodilla.com/browse/WDP201001-41

2020-10-22 18:58 UTC, lukaszewczak requested changes
Basiu świetna robota. Komponenet prezentuje się dobrze, zostało kilka niuansów do poprawy ale nie powinny przysporzyć Ci kłopotu

2020-10-22 18:58 UTC, lukaszewczak commented on src/components/views/ProductPage/ProductPage.js
> +            </div>
Basiu przenieś tą część do oddzielnego komponentu, dzięki temu będzie stanowił niezależny fragment łatow zarządzalny

2020-10-22 18:58 UTC, lukaszewczak commented on src/components/views/ProductPage/ProductPage.module.scss
> +        background-color: $orange;
Basiu zwróć uwagę, że w całym pliku scss korzystasz ze zmiennych do kolorów które nie powinny byc używane bezpośrednio w kodzie, zgodnie z ostantimi zmianami w pliku settings. Potrezbne sa dedykowane zmienne dla tego obszaru

2020-10-23 07:58 UTC, akijania commented
Basiu zobacz czy konsola nie wyrzuca Ci błędów. Na pewno a bez odpowiedniego href pojawia się w konsoli jako błąd.

2020-10-23 16:50 UTC, BasiaM1 commented on src/components/views/ProductPage/ProductPage.js
> +            </div>
ok przeniosę

2020-10-23 16:52 UTC, BasiaM1 commented
> Basiu zobacz czy konsola nie wyrzuca Ci błędów. Na pewno a bez odpowiedniego href pojawia się w konsoli jako błąd.

jasne zapomniałam o href

2020-10-24 02:43 UTC, lukaszewczak requested changes

2020-10-24 02:43 UTC, lukaszewczak commented on src/components/views/ProductPage/ProductPage.js
> +            <ProductView />
Nowy komponenet oczekuje następujących propsów a ich nie dostał. Dlatego gwazdki nie działają poprawnie.
```
id: PropTypes.string.isRequired,
stars: PropTypes.number,
isStarred: PropTypes.bool,
```

Przenieś też `ProductView` poza  `<div className='container'>` w razie potrzeby taki kontener zdefiniuj w `ProdutView`.

2020-10-24 02:43 UTC, lukaszewczak commented on src/components/features/ProductView/ProductView.js
> +const ProductView = ({ id, stars, isStarred }) => {
Popracuj njeszcze nad nazwą tego komponenetu, aby bardziej nawiązywał do tego co jest prezentowane. Tu mamy tylko fragment opisu produktu zawierający: pełny opis, opinie, specyfikacje i inne. ProductView może sugerować pełny podgląd produktu

2020-10-24 16:24 UTC, lukaszewczak commented
@BasiaM1 Popraw proszę konflikty

2020-10-24 19:23 UTC, lukaszewczak approved these changes

2020-10-24 19:24 UTC, lukaszewczak commented
@MaciekLubocki @BasiaM1 @akijania @koniecznytomek @EdytaW zapoznajcie sie z tym PR-em, zgłoście ewntualne uwagi lub dajcie approve

2020-10-24 19:29 UTC, mariannasowi approved these changes
Super Basiu :)

2020-10-24 19:36 UTC, merged