WIP: WDP201001-70
lukaszewczak/WDP-2010-01 pull request #58
Opened 2020-10-22 21:29 UTC by EdytaW

Link do zadania: https://projects.kodilla.com/browse/WDP201001-70

Dodałam CountComments, który ma zliczać liczbę komentarzy w LatestBlog. Funkcja wymaga jeszcze zmian żeby dla poszczególnych postów wyświetlała się poprawna ilość komentarzy.

2020-10-23 03:20 UTC, lukaszewczak commented
Popraw proszę konflikty

2020-10-23 03:38 UTC, lukaszewczak requested changes

2020-10-23 03:38 UTC, lukaszewczak commented on src/components/common/LastPost/LastPost.js
> +            <CountComments />
`<FontAwesomeIcon icon={faComment}></FontAwesomeIcon>` przenieś do tego nowego komponentu `CountCommets`

2020-10-23 03:38 UTC, lukaszewczak commented on src/components/common/LastPost/LastPost.js
> +import CountComments from '../../features/CountComments/CountCommentsContainer';
Nie potrzebujesz do tego kontenera, `LastPost` otrzymuje już propsa `comments` któego możesz przekazać do swojego komponentu `<CountComments>`

2020-10-23 03:38 UTC, lukaszewczak commented on src/components/features/CountComments/CountComments.js
> +class CountComments extends React.Component {
Prosty komponenet funkcyjny w zupełnosci do tego wystarczy a nie klasa

2020-10-23 03:38 UTC, lukaszewczak commented on src/components/features/CountComments/CountComments.js
> +  ),
Ten komponenet potrzebuje tylko dostać listę komentarzy

2020-10-23 03:38 UTC, lukaszewczak commented on src/components/features/CountComments/CountComments.js
> +    });
To jest błędny sposób liczenai sumy, ale tutaj nie będzie to potrzebne, komponenet otrzyma tylko tablicę komentarzy z której łatwo pobrać długość

2020-10-23 19:07 UTC, akijania commented on src/components/features/CountComments/CountComments.js
> +      <FontAwesomeIcon icon={faComment}></FontAwesomeIcon> {comments.length}
Dopisz jeszcze słowo 'comments' żeby było widać czego dotyczy ta liczba

2020-10-24 03:00 UTC, lukaszewczak approved these changes

2020-10-24 03:01 UTC, lukaszewczak commented
@akijania @mariannasowi Proszę o uwagi lub approve

2020-10-24 07:30 UTC, akijania approved these changes

2020-10-24 12:03 UTC, mariannasowi approved these changes

2020-10-24 16:24 UTC, merged