Add products compare
lukaszewczak/WDP-2010-01 pull request #6
Opened 2020-10-07 16:40 UTC by koniecznytomek

Porównywarka ustawia reduksowy stan z produktami. Max można ustawić 4, zrobiłem zabezpieczenie przed możliwością dodania dwóch, tych samych produktów (nie da się ich wrzucić, button nie reaguje - można ewentualnie stworzyć dodatkowo alert albo jakiś popup). Nie wiem, czy dobrze zrozumiałem opis co do ikonki pod produktem? 

https://projects.kodilla.com/secure/RapidBoard.jspa?rapidView=120&projectKey=WDP201001&view=detail&selectedIssue=WDP201001-12

2020-10-07 19:16 UTC, lukaszewczak requested changes

2020-10-07 19:16 UTC, lukaszewczak commented on src/components/features/ProductsCompare/ProductsCompare.module.scss
> +    border-bottom: 1px solid #000;
Kolory do zmiennych

2020-10-07 19:16 UTC, lukaszewczak commented on src/components/features/ProductsCompare/ProductsCompare.js
> +  if (products.length > 0) {
Upewnij się, czy `products` istnieje, w linii 20 już np taką weryfikację robisz

2020-10-07 19:16 UTC, lukaszewczak commented on src/components/features/ProductsCompare/ProductsCompare.js
> +  const products = compare.products;
`compare` nie jest wymaganym propsem i może nie być ustawiony, przed probraniem `products` należy sprawdzic czy obiekt `compare` istnieje, albo asygnalizuj, że obiekt `compare` jest wymaganym propsem

2020-10-07 19:16 UTC, lukaszewczak commented on src/components/features/ProductsCompare/ProductsCompare.module.scss
> +    opacity: 1 !important;
Czy `!important` jest naprawdę konieczny?

2020-10-07 19:16 UTC, lukaszewczak commented on src/components/common/ProductBox/ProductBox.js
> +    if (isExist !== true)
Dodaj klamry do tego if-a aby było czytelniej i lepiej było widać blok kodu który odnosi się do ifa

2020-10-07 19:16 UTC, lukaszewczak commented on src/components/common/ProductBox/ProductBox.js
> +      // prevent to add the same product to compare
Ten komentarz nie jest nam potrzebny, można bardzije rozszerzyć nazwę zmiennej `isExists` na np `isProductAddedToCompare`

2020-10-07 19:16 UTC, lukaszewczak commented on src/components/common/ProductBox/ProductBox.js
> +        : alert('You can compare maximum of 4 products!');
Zapisz tą 4 pod stałą i użyj jej w kodzie i w komunikacie wyświetlanym dla użytkownika. łatwiej to ędize zmienić w przyszłości

2020-10-07 19:16 UTC, lukaszewczak commented on src/components/features/ProductsCompare/ProductsCompare.js
> +  products: PropTypes.array,
Czy te propsy są opcjonalne?

2020-10-07 19:16 UTC, lukaszewczak commented on src/components/common/ProductBox/ProductBox.js
> +  compare: PropTypes.object,
Czy te nowe propsy są opcjonalne?

2020-10-08 02:43 UTC, lukaszewczak commented
Popraw proszę konflikty

2020-10-08 08:32 UTC, lukaszewczak commented
@koniecznytomek Popraw proszę konflikty

2020-10-08 09:07 UTC, lukaszewczak requested changes

2020-10-08 09:07 UTC, lukaszewczak commented on src/components/common/ProductBox/ProductBox.js
> +    const isProductAddedToCompare = compare.products.reduce(
Tu jeszcze upewnij się, że tabela `products` istnieje

2020-10-08 09:07 UTC, lukaszewczak commented on src/components/features/ProductsCompare/ProductsCompare.js
> +                onClick={() => unsetHandler(product.id)}
Czy konieczna jest ta dodatkowa metoda `unsetHandler` ? Możemy również wywołac bezpośrednio `unsetCompare`

2020-10-08 09:21 UTC, koniecznytomek commented on src/components/features/ProductsCompare/ProductsCompare.js
> +                onClick={() => unsetHandler(product.id)}
Tak też mi po głowie chodziło, czy do tak krótkiej instrukcji potrzeba pisać dodatkowy handler. Już poprawiam.

2020-10-08 10:14 UTC, lukaszewczak approved these changes
Dobra robota :-)

2020-10-08 10:14 UTC, merged