Wdp201001-63
lukaszewczak/WDP-2010-01 pull request #65
Opened 2020-10-26 19:27 UTC by MaciekLubocki

Dodałem do komponentu Furniture element sortowania po kolorach. Link do zadania: 
https://projects.kodilla.com/browse/WDP201001-63

2020-10-26 19:28 UTC, MaciekLubocki commented
@lukaszewczak dodałem zadanie 63. Bardzo proszę o code review. dziękuję.

2020-10-27 03:41 UTC, lukaszewczak requested changes
@MaciekLubocki ogólnie spoko, kilka niuansów zostało

2020-10-27 03:41 UTC, lukaszewczak commented on src/components/common/FilterByColor/FilterByColor.js
> +        {colors.map(({ name }, index) => (
Upewij się, że tablica `colors` istnieje

2020-10-27 03:41 UTC, lukaszewczak commented on src/components/common/FilterByColor/FilterByColor.js
> +            )}
Zamiast powtarzać kod, proponuje użyć operatora warunkowego na samym propsie `className` czyli `activeColor === name ? style.activeText : stles.text`

2020-10-27 03:41 UTC, lukaszewczak commented on src/components/common/FilterByColor/FilterByColor.module.scss
> +.Text {
Dlaczego ta klasa jest z wielkiej litery?

2020-10-27 13:20 UTC, BasiaM1 reviewed
Nie zauważyłam błędów, po naniesieniu tych poprawek od Łukasza będzie ok:)

2020-10-27 15:20 UTC, MaciekLubocki commented on src/components/common/FilterByColor/FilterByColor.js
> +        {colors.map(({ name }, index) => (
@lukaszewczak, update zrobiony.

2020-10-27 15:21 UTC, MaciekLubocki commented on src/components/common/FilterByColor/FilterByColor.js
> +            )}
@lukaszewczak, zmieniłem kod zgodnie z wytycznymi.

2020-10-27 15:21 UTC, MaciekLubocki commented on src/components/common/FilterByColor/FilterByColor.module.scss
> +.Text {
@lukaszewczak literówka, poprawiłem.

2020-10-27 15:22 UTC, MaciekLubocki commented
@lukaszewczak, @BasiaM1  Basia dziekuje za przejrzenie kodu. Łukasz poprawiłem wg Twoich wskazówek. Mam nadzieję, że teraz będzie ok.

2020-10-27 15:40 UTC, lukaszewczak approved these changes

2020-10-27 16:03 UTC, mariannasowi approved these changes

2020-10-27 20:23 UTC, merged